/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginpage;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author patatuffolo
 */
public class CHATS_Chat extends javax.swing.JFrame {

    /**
     * Creates new form Chat
     */
    //CONNECTION
    Connection connection = null;
    Connection connection0 = null;
    PreparedStatement statement = null;
    ResultSet results = null;
    Statement st = null;
    int result;
    boolean a = true;
    int i = 0;
    public String Host = "sql11.freemysqlhosting.net",
                  dbName = "sql11422997",
                  //tName = "Users",
                  dbUsername = "sql11422997",
                  dbPassword = "2yWXfclRIe";

    public CHATS_Chat() {
        initComponents();
        try {
            connection = DriverManager.getConnection("jdbc:mysql://" + Host + "/" + dbName + "?user=" + dbUsername + "&password=" + dbPassword);
            //connection = lgn.connection; //prova se funziona così
            statement = connection.prepareStatement("CREATE TABLE " + CHATS_Login.chatName + " (Id INT PRIMARY KEY AUTO_INCREMENT, Alert VARCHAR(1), Sender VARCHAR(40), Message TEXT, Admin VARCHAR(40), Time TEXT);");
            result = statement.executeUpdate();
            System.out.println("Created Table");
            //Dai il chatAdmin
            try {
                //connection0 = DriverManager.getConnection("jdbc:mysql://192.168.64.2/Users?user=Patatuffolo&password=Ih]aa4kpeAB2*MF!");
                String time = new SimpleDateFormat("HH:mm:ss").format(Calendar.getInstance().getTime());
                statement = connection.prepareStatement("INSERT INTO " + CHATS_Login.chatName + " (Alert, Sender, Message, Admin, Time) VALUES" + "('T','chatAdmin:', '" + CHATS_Login.username + "', '" + CHATS_Login.username + "','" + time + "')");
                result = statement.executeUpdate();
                System.out.println(CHATS_Login.username + " is the chat admin of chat: " + CHATS_Login.chatName);
                //Ih]aa4kpeAB2*MF!
            } catch (SQLException ex) {
                System.out.println("Coundn't give chatAdmin: " + ex);
            }
            //Ih]aa4kpeAB2*MF!
        } catch (SQLException ex) {
            System.out.println("Coundn't create table: " + ex);
        }

        this.setTitle("UnIdEnTiFiEd - " + CHATS_Login.chatName.split("CHAT_")[1] + ", connected As:" + CHATS_Login.username);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(62, 68, 81));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(62, 68, 81));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(243, 235, 235));
        jTextArea1.setRows(5);
        jTextArea1.setText("QUICK START:\n- Type Something to start the conversation.\n- Press Enter to send the message.\n- Type END to destroy the current Chat. (Requires chat Admin)\n- Type OUT to leave the Chat.\n- Type HELP to view this commands.");
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setBackground(new java.awt.Color(243, 235, 235));
        jTextField1.setFont(new java.awt.Font("Courier New", 0, 13)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(62, 68, 81));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        //Non serve
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER /*  KeyEvent.VK_ENTER  */) {
            //COPIATO
            String u1 = CHATS_Login.username;
            String testo1 = jTextField1.getText();
            jTextField1.setText("");

            try {
                st = connection.createStatement();
            } catch (SQLException ex) {
                System.out.println("Couldn't Create Statement:\n" + ex);
            }

            if (!testo1.toLowerCase().equals("end") && !testo1.toLowerCase().equals("out") && !testo1.toLowerCase().equals("") && !testo1.toLowerCase().equals("help")) {
                try {
                    String time = new SimpleDateFormat("HH:mm:ss").format(Calendar.getInstance().getTime());
                    st.executeUpdate("INSERT INTO " + CHATS_Login.chatName + " (Alert, Sender, Message, Time) VALUES" + "('F','" + u1 + "', '" + testo1 + "','" + time + "')");
                    showMessages();
                } catch (SQLException ex) {
                    System.out.println("Couldn't Insert Data Values:\n" + ex);
                }
            } else if (testo1.toLowerCase().equals("end")) {
                try {
                    delChat();
                    //Ih]aa4kpeAB2*MF!
                    //bho -> connection.close();
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
            } else if (testo1.toLowerCase().equals("out")) {

                lgn lgn = new lgn();
                lgn.setVisible(true);
                this.dispose();
            }
            else if (testo1.toLowerCase().equals("help")) {
                CHATS_Instructions help = new CHATS_Instructions();
                help.setVisible(true);
            }
            ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);
            executor.scheduleAtFixedRate(update, 0, 2, TimeUnit.SECONDS);
            if (!a) {
                executor.shutdown();
            }

            //FINE COPIA
        }
    }//GEN-LAST:event_jTextField1KeyPressed
    
    Runnable update = new Runnable() {
        public void run() {
            showMessages();
        }
    };

    public void delChat() throws SQLException {
        statement = connection.prepareStatement("SELECT * FROM " + CHATS_Login.chatName + " WHERE Id = '1'");
        results = statement.executeQuery();
        results.next();
        if (results.getString("Admin").equals(CHATS_Login.username)) {
            try {
                a = false;
                st.executeUpdate("DROP TABLE " + CHATS_Login.chatName + ";");
                System.out.println("Chat Deleted");

                CHATS_Login lg = new CHATS_Login();
                lg.setUsername();
                lg.setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                System.out.println("Couldn't delete the table: " + CHATS_Login.chatName + " cause: \n" + ex);
            }
        } else {
            System.out.println("You're not the chat admin!");
            //Name tried to close che chat but couldn't
            try {
                String time = new SimpleDateFormat("HH:mm:ss").format(Calendar.getInstance().getTime());
                st.executeUpdate("INSERT INTO " + CHATS_Login.chatName + " (Alert, Sender, Message, Time) VALUES" + "('T','" + CHATS_Login.username + "','Tried to close this chat','" + time + "')");
                showMessages();
            } catch (SQLException ex) {
                System.out.println("Couldn't Insert Data Values:\n" + ex);
            }
        }
    }

    public void showMessages() {
        //Check wheter there are NEW messages.
        try {
            statement = connection.prepareStatement("SELECT * FROM " + CHATS_Login.chatName);
            results = statement.executeQuery();
            //Ih]aa4kpeAB2*MF!
            
            jTextArea1.setText("");
            while (results.next()) {
                if (results.getString("Alert").equals("F")) {
                    int id = results.getInt(1);
                    String time = results.getString("Time");
                    String nome = results.getString("Sender");
                    String testo = results.getString("Message");
                    System.out.println(nome + " : " + testo);
                    jTextArea1.append(time + " -> " + nome + ": " + testo + "\n");
                } else {
                    int id = results.getInt(1);
                    String time = results.getString("Time");
                    String nome = results.getString("Sender");
                    String testo = results.getString("Message");
                    System.out.println(nome + " : " + testo);
                    jTextArea1.append(time + "UnIdEnTiFiEd: " + " -> " + nome + " : " + testo + "\n");
                }
            }
            //jTextArea1.setAutoscrolls(true);
        } catch (SQLException ex) {
            System.out.println(ex);
            jTextArea1.setText("Sorry, an UnIdEnTiFiEd sources closed the chat and destroyed all the messages.");
            //DONE -> I MESSAGGI DI ERRORE POTREI SEGNALARLI IN ROSSO RICONOSCENDOLI DA UN T/F COLUMN NELLA TABELLA DELLA CHAT <- DONE
        }
        /**
         *  DefaultCaret caret = (DefaultCaret)jTextArea1.getCaret();
            caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
         */
        
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CHATS_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CHATS_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CHATS_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CHATS_Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CHATS_Chat().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
